blank_issues_enabled: false
contact_links:
  - name: "â‰ï¸ Unsure if this is a bug, idea or support request ğŸ‘‰ please open a discussion ğŸ‘ˆ"
    url: https://github.com/emacscollective/borg/discussions/categories/general
    about: Start a discussion without having to specify its kind upfront.
  - name: "ğŸ’• Please support my work on Borg and other Emacs projects"
    url: https://github.com/sponsors/tarsius
    about: Thanks! Any support helps. These donations from users are my only income.
  - name: "ğŸ’¡ Suggest a feature ğŸ‘‰ please open a discussion instead of an issue ğŸ‘ˆ"
    url: https://github.com/emacscollective/borg/discussions/categories/ideas
    about: Start a discussion suggesting an improvement or a new feature.
  - name: "ğŸ†˜ Ask the maintainers for support ğŸ‘‰ please open a discussion ğŸ‘ˆ"
    url: https://github.com/emacscollective/borg/discussions/categories/support
    about: Start a discussion asking for help.
  - name: "â„¹ï¸ Borg Manual"
    url: https://docs.emacsmirror.org/borg
    about: The fine manual may also be of use.
